### ISSUE TITLE
DataStore Test

### ISSUE THREAD

**Issue by LindenY** [LindenY/asw4j#9]
It now introduced two new objects, Balancer and Combiner. It has not been tested yet. @ChengJoyceJi

**Comment by LindenY** [comment]
Take my loneliness a step further. I now open issues, close issues and assign issues to myself.....
@ChengJoyceJi

**Comment by ChengJoyceJi** [comment]
@LindenY Haha have fun in your own zone!! You can assign to me if you feel i am able to do it. xD

**Comment by LindenY** [comment]
I think you are able to do it, but i dont you would have time to do it. Ji3lang @ChengJoyceJi

**Comment by ChengJoyceJi** [comment]
I do have time sometimes lol. lin pp, why are you going to lang again tonight?

**Comment by LindenY** [comment]
Xiaobiaozi, you are going to lang after lang tonight. You are now Ji5lang

**Comment by ChengJoyceJi** [comment]
What the hell... i'm eventually going back home tonight !! not lang~

**Comment by LindenY** [comment]
~~~~~~~~~~~~ after ~~~~~~~~~~~~~~~ and after ~~~~~~~~~~~~~~~~~~
lang li bai tiao, JiQianLang~~~~~

**Comment by ChengJoyceJi** [comment]
xiaobiaozi, ni hen kuang ma~~~~~

**Comment by LindenY** [comment]
```
```

**Comment by LindenY** [comment]
``` dong?
```
